repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
